apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service_test_1
    links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
    - url: https://example.com/group
      title: Example Group
      icon: group
    - url: https://example.com/cloud
      title: Link with Cloud Icon
      icon: cloud
    - url: https://example.com/dashboard
      title: Dashboard
      icon: dashboard
    - url: https://example.com/help
      title: Support
      icon: help
    - url: https://example.com/web
      title: Website
      icon: web
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/Maximilian-Fuss/yamltest/tree/main/docs/doc_test_1
  namespace: default
spec:
  type: service
  lifecycle: test_lifecycle
  owner: test_owner
  providesApis:
    - api_test_1
    - api_test_2
