apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service_test_1
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/Maximilian-Fuss/yamltest
  namespace: default
spec:
  type: service
  lifecycle: test_lifecycle
  owner: test_owner
  providesApis:
    - api_test_1
    - api_test-2
